name: Create a package artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload packages.zip
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
